name: Notify Stats

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  count-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Count Markdown files
        id: count
        run: |
          count=$(find . -type f -name "*.md" | wc -l)
          echo "md_count=$count" >> $GITHUB_OUTPUT
          echo "$count" > .github/.md-count.log
          echo "Markdown files count: $count"

      - name: Restore previous count
        id: previous
        run: |
          git fetch origin main
          if git show origin/main:.md-count.log > old_count.txt 2>/dev/null; then
            prev_count=$(cat old_count.txt)
          else
            prev_count=0
          fi
          echo 'prev_count=$prev_count'
          echo "prev_count=$prev_count" >> $GITHUB_OUTPUT

      - name: echo log file
        run: cat .github/.md-count.log

      - name: 💬 Notify if count has changed
        if: steps.count.outputs.md_count != steps.previous.outputs.prev_count
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEV }}
          CURRENT_COUNT: ${{ steps.count.outputs.md_count }}
          PREVIOUS_COUNT: ${{ steps.previous.outputs.prev_count }}
        run: |
          diff=$((CURRENT_COUNT - PREVIOUS_COUNT))
          deno run --allow-env --allow-net .github/scripts/notify-stats.ts $PREVIOUS_COUNT $CURRENT_COUNT